#!/usr/bin/env sh

node scripts/auto-log-commit.cjs --hook commit-msg --message-file "$1"
status=$?

if [ $status -ne 0 ]; then
  echo "Auto change-log hook failed while reading commit message. Commit aborted."
fi

exit $status
